---
title: "Untitled"
author: "Satoshi"
date: "5/4/2019"
output: html_document
---

```{r, echo = FALSE}
library(dplyr)
library(meta)
library(metafor)
library(foreign)
library(readxl)
library(dosresmeta)
library(ggplot2)
library(stargazer)
library(compute.es)
```

```{r}
df <- read.csv("EPI233_meta_analysis.csv")

df<-df%>%dplyr::select("author","year","location","design","setting","icu_type","age_cat","mean_median_age","age_cat_2","N","male","MV_duration","steroid","cum_dose_equi_hydro","mean_time_first_dosing","observation_period","n_control_gibleed","event_control_gibleed","n_steroid_gibleed","event_steroid_gibleed","n_control_hyperglycemia","event_control_hyperglycemia","n_steroid_hyperglycemia","event_steroid_hyperglycemia","n_control_stridor","event_control_stridor","n_steroid_stridor","event_steroid_stridor","n_control_reintubation","event_control_reintubation","n_steroid_reintubation","event_steroid_reintubation")
head(df)

edema <- df %>% # keep only relevant rows
        filter(!is.na(year)) %>% arrange(year)
# "edema" is the name of our working dataset!

edema <- edema %>% #change column names: upper case to lower case
        rename(n = N, mv_duration = MV_duration) 
```

# Table 1: Description
```{r}
table1 <- edema %>%
  dplyr::select(author, year, cum_dose_equi_hydro, observation_period, mean_time_first_dosing)
stargazer(table1, summary = FALSE, type = "text")
```

# Stridor & RCT
```{r}
edema_rct_str<-edema%>%filter(design=="RCT", !is.na(n_control_stridor))
```

```{r}
# stridor & RCT: fixed effects
#Fixed-effect (RR)
meta_fix<-metabin(event_steroid_stridor,n_steroid_stridor,event_control_stridor,n_control_stridor,data=edema_rct_str,studlab=paste(author,year),comb.fixed=T,comb.random=F,sm="RR")
forest(meta_fix,lab.e="Steroid")

#Fixed-effect (RD)
#meta_fix<-metabin(event_steroid_stridor,n_steroid_stridor,event_control_stridor,n_control_stridor,data=edema_rct_str,studlab=paste(author,year),comb.fixed=T,comb.random=F,sm="RD")
#forest(meta_fix,lab.e="Steroid")

#Fixed-effect (OR)
#meta_fix<-metabin(event_steroid_stridor,n_steroid_stridor,event_control_stridor,n_control_stridor,data=edema_rct_str,studlab=paste(author,year),comb.fixed=T,comb.random=F,sm="OR",method = "MH")
#forest(meta_fix,lab.e="Steroid")

#Fixed-effect (OR, method = peto)
#meta_fix<-metabin(event_steroid_stridor,n_steroid_stridor,event_control_stridor,n_control_stridor,data=edema_rct_str,studlab=paste(author,year),comb.fixed=T,comb.random=F,sm="OR", methods = "Peto")
#forest(meta_fix,lab.e="Steroid")
```

```{r, fig.width = 5}
# stridor & RCT: random effects
#Random-effect (RR)
meta_ran<-metabin(event_steroid_stridor,n_steroid_stridor,event_control_stridor,n_control_stridor,data=edema_rct_str,studlab=paste(author,year),comb.fixed=F,comb.random=T,sm="RR",method.tau = "DL")
forest(meta_ran,lab.e="Steroid")

# random-effect (RD)
#meta_ran<-metabin(event_steroid_stridor,n_steroid_stridor,event_control_stridor,n_control_stridor,data=edema_rct_str,studlab=paste(author,year),comb.fixed=F,comb.random=T,sm="RD",method.tau = "EB")
#forest(meta_ran,lab.e="Steroid")

# random-effect (OR)
meta_ran<-metabin(event_steroid_stridor,n_steroid_stridor,event_control_stridor,n_control_stridor,data=edema_rct_str,studlab=paste(author,year),comb.fixed=F,comb.random=T,sm="OR",method.tau = "DL")
forest(meta_ran,lab.e="Steroid")

OR=c(0.40,0.21,0.79)
PEER=(4+23+10+28+11+12+7)/226
NNT = (1-(PEER*(1-OR))) / ((1-PEER)*(PEER)*(1-OR))
1000/NNT
```

```{r}
#checking publication bias
#Funnel plot
funnel(meta_ran)

eggers.test<-function(data){

  data<-data
  eggers<-metabias(data,k.min=7)
  intercept<-as.numeric(eggers$estimate[1])
  intercept<-round(intercept,digits=3)
  se.intercept<-eggers$estimate[2]
  lower.intercept<-as.numeric(intercept-1.96*se.intercept)
  lower.intercept<-round(lower.intercept,digits = 2)
  higher.intercept<-as.numeric(intercept+1.96*se.intercept)
  higher.intercept<-round(higher.intercept,digits = 2)
  ci.intercept<-paste(lower.intercept,"-",higher.intercept)
  ci.intercept<-gsub(" ", "", ci.intercept, fixed = TRUE)
  intercept.pval<-as.numeric(eggers$p.value)
  intercept.pval<-round(intercept.pval,digits=5)
  eggers.output<-data.frame(intercept,ci.intercept, intercept.pval)
  names(eggers.output)<-c("intercept","95%CI","p-value")
  title<-"Results of Egger's test of the intercept"
  
print(title)
print(eggers.output)
}
eggers.test(data=meta_ran)

```

```{r}
#meta-regression
output_metareg<-metareg(meta_ran,cum_dose_equi_hydro)
bubble(output_metareg,xlim=c(0,80),ylim=c(-2,2),studlab = TRUE,cex.studlab=0.6,pos=3)

output_metareg<-metareg(meta_ran,mean_median_age)
bubble(output_metareg,xlim=c(-1,8),ylim=c(-2,2),studlab = TRUE,cex.studlab=0.6,pos=3)

output_metareg<-metareg(meta_ran,mean_time_first_dosing)
bubble(output_metareg,xlim=c(-1,12),ylim=c(-2,2),studlab = TRUE,cex.studlab=0.6,pos=3)
```

```{r, fig.width = 5}
# stridor & rct: subgroup analysis by age_cat_2 (0, 1), 2(excluded)
meta_sub <- metabin(event_steroid_stridor, n_steroid_stridor, event_control_stridor, n_control_stridor, 
                    data = edema_rct_str, studlab = paste(author,year), 
                    subset = age_cat_2 <= 1, byvar = age_cat_2, 
                    comb.fixed = F,comb.random = T, sm = "RR" , method.tau = "DL")
forest(meta_sub, lab.e = "Steroid")
```

##Re-intubation
```{r}
# new dataframe including only reintubation and RCT
edema_rct_reint<-edema%>%filter(design=="RCT", !is.na(n_control_reintubation))
```

```{r, fig.width = 5}
#Forest
#Fixed-effect (RR)
meta_fix<-metabin(event_steroid_reintubation,n_steroid_reintubation,event_control_reintubation,n_control_reintubation,data=edema_rct_reint,studlab=paste(author,year),comb.fixed=T,comb.random=F,sm="RR")
forest(meta_fix, lab.e="Steroid")

#Fixed-effect (RD)
meta_fix<-metabin(event_steroid_reintubation,n_steroid_reintubation,event_control_reintubation,n_control_reintubation,data=edema_rct_reint,studlab=paste(author,year),comb.fixed=T,comb.random=F,sm="RD")
forest(meta_fix, lab.e="Steroid")

#Fixed-effect (OR "MH")
meta_fix<-metabin(event_steroid_reintubation,n_steroid_reintubation,event_control_reintubation,n_control_reintubation,data=edema_rct_reint,studlab=paste(author,year),comb.fixed=T,comb.random=F,sm="OR", method = "MH")
forest(meta_fix, lab.e="Steroid")

#Fixed-effect (OR "Peto")
meta_fix<-metabin(event_steroid_reintubation,n_steroid_reintubation,event_control_reintubation,n_control_reintubation,data=edema_rct_reint,studlab=paste(author,year),comb.fixed=T,comb.random=F,sm="OR", method = "Peto")
forest(meta_fix, lab.e="Steroid")

OR=c(0.36,0.22,0.59)
PEER=(4+4+4+7+5+33+19+1)/277
NNT = (1-(PEER*(1-OR))) / ((1-PEER)*(PEER)*(1-OR))
1000/NNT
```

```{r}
#Random-effect
meta_ran<-metabin(event_steroid_reintubation,n_steroid_reintubation,event_control_reintubation,n_control_reintubation,data=edema_rct_reint,studlab=paste(author),comb.fixed=F,comb.random=T,sm="RR",method.tau = "EB")
forest(meta_ran,lab.e="Steroid")
```

```{r}
#Funnel plot
funnel(meta_fix)
eggers.test(data=meta_fix)
```

```{r}
#meta-regression
output_metareg<-metareg(meta_fix,cum_dose_equi_hydro)
bubble(output_metareg,xlim=c(0,80),ylim=c(-3,2),studlab = TRUE,cex.studlab=0.6,pos=3)

output_metareg<-metareg(meta_fix,mean_median_age)
bubble(output_metareg,xlim=c(-1,8),ylim=c(-3,2),studlab = TRUE,cex.studlab=0.6,pos=3)

output_metareg<-metareg(meta_fix,mean_time_first_dosing)
bubble(output_metareg,xlim=c(-1,12),ylim=c(-3,2),studlab = TRUE,cex.studlab=0.6,pos=3)
```

```{r, fig.width = 5}
# reintubation & RCT: subgroup analysis by age_cat_2 (0: under 1yr, 1: older than 1 yr), 2(excluded)
meta_sub <- metabin(event_steroid_reintubation, n_steroid_reintubation, event_control_reintubation, n_control_reintubation, 
                    data = edema_rct_reint, studlab = paste(author, year), 
                    subset = age_cat_2 <= 1, byvar = age_cat_2, 
                    comb.fixed = F,comb.random = T, sm = "OR" , method = "Peto")
forest(meta_sub, lab.e = "Steroid")
```
